/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HorizontalBar: typeof import('./src/components/HorizontalBar.vue')['default']
    MapChart: typeof import('./src/components/MapChart.vue')['default']
    RadarBar: typeof import('./src/components/RadarBar.vue')['default']
    Relation: typeof import('./src/components/Relation.vue')['default']
    RingBar: typeof import('./src/components/RingBar.vue')['default']
    TotalData: typeof import('./src/components/TotalData.vue')['default']
    VerticalBar: typeof import('./src/components/VerticalBar.vue')['default']
    WordCloud: typeof import('./src/components/WordCloud.vue')['default']
  }
}
